trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Django settings
  DJANGO_SETTINGS_MODULE: 'InvoiceValidator.settings'
  PYTHON_VERSION: '3.11'
  # Note: Update to the version of Python your project uses

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    addToPath: true

- script: |
    python -m venv env
    source env/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
    python manage.py collectstatic --noinput
  displayName: 'Install dependencies'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<Your Azure Subscription>'
    appType: 'webAppLinux'
    appName: '<Your Web App Name>'
    package: '$(System.DefaultWorkingDirectory)/**/InvoiceValidator' 
  displayName: 'Deploy to Azure WebApp'